#!/bin/sh

## arch linux

sudo pacman -S kitty fzf zsh tmux

# dependency
sudo pacman -S ruby xsel

# oh-my-zsh plugin
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

yay -S bat exa

TP="${HOME}/.tmux_plugins"
mkdir ${TP}
git clone https://github.com/tmux-plugins/tmux-yank ${TP}/yank
git clone https://github.com/tmux-plugins/tmux-cpu ${TP}/cpu
git clone https://github.com/tmux-plugins/tmux-sensible $TP/sensible
git clone https://github.com/schasse/tmux-jump $TP/jump

# tmux-tmp
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
